In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
deno = np.amax(X,axis=0)
print("Demo",deno)
X = X/deno
y = y/100
print(X)
print(y)



def sigmoid (x):
    return 1/(1 + np.exp(-x))

def derivatives_sigmoid(x): 
    return x * (1 - x)

iteration = 100
error_rate =0.1
inputlayer_neurons = 2
hiddenlayer_neurons = 3
output_neurons = 1


weight_hidden = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bias_hidden = np.random.uniform(size=(1,hiddenlayer_neurons))
weight_output = np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bias_output = np.random.uniform(size=(1,output_neurons))
print(X.shape)

for i in range(iteration):
    hidden_input=np.dot(X,weight_hidden)
    hidden_input =hidden_input + bias_hidden
    output_hidden_layer = sigmoid( hidden_input)
    actual_output = np.dot(output_hidden_layer,weight_output)+bias_output
    y_output = sigmoid(actual_output)
    
    
    
    EO = y-y_output
    outgrad = derivatives_sigmoid(y_output)
    d_output = EO* outgrad
    EH = d_output.dot(weight_output.T)
    hiddengrad = derivatives_sigmoid(output_hidden_layer)
    d_hiddenlayer = EH * hiddengrad
    
    weight_output += output_hidden_layer.T.dot(d_output) *error_rate 
    weight_hidden += X.T.dot(d_hiddenlayer) *error_rate

print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,y_output)

Demo [3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
(3, 2)
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.85933652]
 [0.83839621]
 [0.86171999]]
