In [2]:

import pandas as pd
import numpy as np
X = np.random.randint(10,50,100).reshape(20,5) 
print(X)

X_meaned = X - np.mean(X , axis = 0)
print(X_meaned)

cov_mat = np.cov(X_meaned , rowvar = False)
print(cov_mat)

eigen_values , eigen_vectors = np.linalg.eigh(cov_mat)
print("Eigen Values are", eigen_values)
print("Eigen Vectors are", eigen_vectors)

sorted_index = np.argsort(eigen_values)[::-1]
print("The Sorted Eigen Values are", sorted_index)
sorted_eigenvalue = eigen_values[sorted_index]
sorted_eigenvectors = eigen_vectors[:,sorted_index]
print("The Sorted Eigen Vectors are", sorted_eigenvectors)

n_components = 2 
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
print(eigenvector_subset)

X_reduced = np.dot(eigenvector_subset.transpose(),X.transpose()).transpose()
print(X_reduced)


[[32 34 42 44 48]
 [35 31 48 11 15]
 [32 19 33 41 43]
 [33 47 32 11 11]
 [16 39 42 24 14]
 [30 31 30 27 19]
 [45 40 43 19 28]
 [14 33 35 38 25]
 [47 29 21 49 23]
 [24 34 48 37 21]
 [11 21 11 10 15]
 [17 35 27 46 26]
 [18 17 12 16 23]
 [30 46 36 48 42]
 [26 29 28 49 14]
 [34 46 21 22 19]
 [11 31 47 16 29]
 [14 10 42 16 15]
 [19 47 18 43 34]
 [41 46 19 32 45]]
[[  5.55   0.75  10.25  14.05  22.55]
 [  8.55  -2.25  16.25 -18.95 -10.45]
 [  5.55 -14.25   1.25  11.05  17.55]
 [  6.55  13.75   0.25 -18.95 -14.45]
 [-10.45   5.75  10.25  -5.95 -11.45]
 [  3.55  -2.25  -1.75  -2.95  -6.45]
 [ 18.55   6.75  11.25 -10.95   2.55]
 [-12.45  -0.25   3.25   8.05  -0.45]
 [ 20.55  -4.25 -10.75  19.05  -2.45]
 [ -2.45   0.75  16.25   7.05  -4.45]
 [-15.45 -12.25 -20.75 -19.95 -10.45]
 [ -9.45   1.75  -4.75  16.05   0.55]
 [ -8.45 -16.25 -19.75 -13.95  -2.45]
 [  3.55  12.75   4.25  18.05  16.55]
 [ -0.45  -4.25  -3.75  19.05 -11.45]
 [  7.55  12.75 -10.75  -7.95  -6.45]
 [-15.45  -2.25  15.25 -13.95  